"""
Database models for research entities
"""
from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field
from enum import Enum


class ResearchDepth(str, Enum):
    """Research depth levels"""
    QUICK = "quick"
    STANDARD = "standard"
    DEEP = "deep"


class SourceType(str, Enum):
    """Types of research sources"""
    WEB = "web"
    ACADEMIC = "academic"
    ARXIV = "arxiv"
    PDF = "pdf"
    BOOK = "book"


class ResearchStatus(str, Enum):
    """Research session status"""
    PENDING = "pending"
    PLANNING = "planning"
    RESEARCHING = "researching"
    ANALYZING = "analyzing"
    VERIFYING = "verifying"
    SYNTHESIZING = "synthesizing"
    GENERATING = "generating"
    COMPLETED = "completed"
    FAILED = "failed"


class ResearchSession(BaseModel):
    """Research session model"""
    id: Optional[str] = None
    user_query: str
    research_goal: Optional[str] = None
    research_depth: ResearchDepth = ResearchDepth.STANDARD
    status: ResearchStatus = ResearchStatus.PENDING
    current_task: Optional[str] = None
    progress: float = 0.0
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None
    report_path: Optional[str] = None
    
    class Config:
        use_enum_values = True


class Source(BaseModel):
    """Research source model"""
    id: Optional[str] = None
    session_id: str
    title: str
    url: Optional[str] = None
    author: Optional[str] = None
    publication_date: Optional[datetime] = None
    source_type: SourceType
    abstract: Optional[str] = None
    doi: Optional[str] = None
    relevance_score: float = 0.0
    credibility_score: float = 0.0
    retrieved_at: datetime = Field(default_factory=datetime.utcnow)
    content: Optional[str] = None
    
    class Config:
        use_enum_values = True


class Evidence(BaseModel):
    """Evidence extracted from sources"""
    id: Optional[str] = None
    session_id: str
    source_id: str
    claim: str
    supporting_text: str
    page_number: Optional[int] = None
    relevance_score: float = 0.0
    extracted_at: datetime = Field(default_factory=datetime.utcnow)


class Claim(BaseModel):
    """Claim that requires verification"""
    id: Optional[str] = None
    session_id: str
    claim_text: str
    is_verified: bool = False
    supporting_evidence_ids: List[str] = Field(default_factory=list)
    confidence_score: float = 0.0
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Citation(BaseModel):
    """Citation information"""
    id: Optional[str] = None
    source_id: str
    citation_text: str
    citation_style: str = "APA"  # APA, MLA, Chicago, etc.


class ResearchPlan(BaseModel):
    """Research plan generated by the agent"""
    session_id: str
    objectives: List[str]
    subtopics: List[str]
    required_evidence: List[str]
    planned_queries: List[str]
    created_at: datetime = Field(default_factory=datetime.utcnow)
